namespace cuvistaWinui
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }

    runtimeclass CustomRuntimeXaml
    {
        CustomRuntimeXaml();
        String displayName { get; };
    }
}
